Feature/add new templates
tweag/jupyterWith pull request #330
Opened 2022-10-26 19:04 UTC by djacu

2022-10-27 08:47 UTC, MMesch commented
Nice. Does this need an update to the top-level `README.md`?

2022-11-02 10:11 UTC, thufschmitt requested changes
A couple suggestions/questions, but looking good overall :+1: 

Definitely not a blocker here, but are these templates somehow tested (or testable)? That would be nice

2022-11-02 10:11 UTC, thufschmitt commented on template/python-flake/flake.nix
> +  inputs.flake-compat.url = "github:edolstra/flake-compat";
What's `flake-compat` used for? Should these templates also include a `default.nix` to take advantage of it?

2022-11-02 10:11 UTC, thufschmitt commented on template/python-flake/flake.nix
> +  inputs.nixpkgs.url = "github:nixos/nixpkgs/1158501e7c7cba26d922723cf9f70099995eb755";
Any reason why this is hardcoded?

If this is just to get a fixed known version, maybe we could ship a (partial) `flake.lock` that pins it (but doesn't prevent `nix flake update` from working)

2022-11-02 10:11 UTC, thufschmitt commented on template/python-flake/flake.nix
> +  inputs.nixpkgs.url = "github:nixos/nixpkgs/1158501e7c7cba26d922723cf9f70099995eb755";
Or have `inputs.nixpkgs.follows = "jupyterWith/nixpkgs"` to make sure that both stay in sync if that's desirable

2022-11-29 07:33 UTC, garbas commented
I'm closing this PR until we finish the UX work (switching to nixos modules) then we can reopen the discussion if we want one or more templates. We will have to fix the issue of discoverability of templates, but we can discuss it once we have nixos modules in place.

2022-11-29 07:33 UTC, closed without merging