Only evaluate julia lazily in flake.nix
tweag/jupyterWith pull request #411
Opened 2023-01-08 21:38 UTC by jaapterwoerds

fixes #410

2023-01-12 21:53 UTC, djacu commented
Hey can you run `alejandra` on the repo and push a new commit? The CI is failing because of the linter.
`alejandra` is in the devShell so you can run

```
nix develop
pre-commit run --all
```

2023-01-16 22:13 UTC, djacu commented on flake.nix
> +              + (lib.strings.optionalString ((lib.lists.count (e: builtins.match ".*julia.*" e.outPath != null) kernelDerivations) > 0) ''
```suggestion
              + (lib.strings.optionalString (
                  builtins.any
                  (kernel: kernel.kernelInstance.language == "julia")
                  kernelDerivations
                )
 ''
```

This should be a bit safe than looking in the outpath of the kernel derivation.

2023-01-16 22:21 UTC, djacu commented on flake.nix
> +                # add Julia for IJulia
Can you modify the scripts that add Julia to be the following. We don't need the `if` statement any more.
```
# add Julia for IJulia
echo 'Adding Julia as an available package.'
for i in ${pkgs.julia-bin}/bin/*; do
  filename=$(basename $i)
  ln -s ${pkgs.julia-bin}/bin/$filename $out/bin/$filename
done
```

2023-01-16 22:22 UTC, djacu commented on flake.nix
> +                # add Julia for IJulia
Can you modify the scripts that add Julia to be the following. We don't need the `if` statement any more.
```
# add Julia for IJulia
echo 'Adding Julia as an available package.'
for i in ${pkgs.julia-bin}/bin/*; do
  filename=$(basename $i)
  ln -s ${pkgs.julia-bin}/bin/$filename $out/bin/$filename
done
```

2023-01-17 10:45 UTC, jaapterwoerds commented
Great suggestions I will update the MR, thanks

2023-01-17 11:10 UTC, jaapterwoerds commented
Sorry for the force push I wasn't aware of the other commits made. I hope it's Ok now

2023-01-18 23:02 UTC, djacu commented
> Sorry for the force push I wasn't aware of the other commits made. I hope it's OK now

No worries. I had just caught the branch up to main so the CI would run properly. Looks like you did the same.

2023-01-18 23:15 UTC, djacu requested changes

2023-01-18 23:15 UTC, djacu commented on flake.nix
> +                '')));
```suggestion
              + (lib.strings.optionalString (
                  builtins.any
                  (kernel: kernel.kernelInstance.language == "julia")
                  kernelDerivations
                ) ''
                  # add Julia for IJulia
                  echo 'Adding Julia as an available package.'
                  for i in ${pkgs.julia-bin}/bin/*; do
                    filename=$(basename $i)
                    ln -s ${pkgs.julia-bin}/bin/$filename $out/bin/$filename
                  done
                ''));
```

Looks like `optionalString` got accidentally doubled up here.

2023-01-18 23:18 UTC, djacu commented on flake.nix
> +                '')));
Hey I'm going to sign off on this so we can get the PR merged and unblock you.

2023-01-18 23:29 UTC, djacu approved these changes
lgtm

2023-01-18 23:29 UTC, merged

2023-01-19 09:07 UTC, jaapterwoerds commented
Thanks for the fix @djacu